sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: whpz-sky-take-out
    access-key-secret: OFGvGCLcxWVhYPIxPigD312NQjvzhT
    access-key-id: LTAI5tA1z7CVhKLjx8jUsHBc
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10